# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kylevess/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kylevess/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/kylevess/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/kylevess/proprietary/bin/atx:system/bin/atx \
    vendor/samsung/kylevess/proprietary/bin/atxd:system/bin/atxd \
    vendor/samsung/kylevess/proprietary/bin/BCM4330B1.hcd:system/bin/BCM4330B1.hcd \
    vendor/samsung/kylevess/proprietary/bin/bcm_dut:system/bin/bcm_dut \
    vendor/samsung/kylevess/proprietary/bin/bkmgrd:system/bin/bkmgrd \
    vendor/samsung/kylevess/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/samsung/kylevess/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/samsung/kylevess/proprietary/bin/btld:system/bin/btld \
    vendor/samsung/kylevess/proprietary/bin/cate_rpc_util:system/bin/cate_rpc_util \
    vendor/samsung/kylevess/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/kylevess/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/kylevess/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/samsung/kylevess/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/kylevess/proprietary/bin/LE_dut:system/bin/LE_dut \
    vendor/samsung/kylevess/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/kylevess/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/kylevess/proprietary/bin/mttlogger:system/bin/mttlogger \
    vendor/samsung/kylevess/proprietary/bin/ndc:system/bin/ndc \
    vendor/samsung/kylevess/proprietary/bin/netcfg:system/bin/netcfg \
    vendor/samsung/kylevess/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/kylevess/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/kylevess/proprietary/bin/p2p_supplicant:system/bin/p2p_supplicant \
    vendor/samsung/kylevess/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/kylevess/proprietary/bin/samsungpowersoundplay:system/bin/samsungpowersoundplay \
    vendor/samsung/kylevess/proprietary/bin/surfaceflinger:system/bin/surfaceflinger \
    vendor/samsung/kylevess/proprietary/bin/usb_portd:system/bin/usb_portd\
    vendor/samsung/kylevess/proprietary/bin/vdc:system/bin/vdc \
    vendor/samsung/kylevess/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/kylevess/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/kylevess/proprietary/etc/DiamondVoice_Filter_WB.txt:system/etc/DiamondVoice_Filter_WB.txt \
    vendor/samsung/kylevess/proprietary/etc/DiamondVoice_WB.txt:system/etc/DiamondVoice_WB.txt \
    vendor/samsung/kylevess/proprietary/etc/DiamondVoice_NB.txt:system/etc/DiamondVoice_NB.txt \
    vendor/samsung/kylevess/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/kylevess/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/kylevess/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/kylevess/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/kylevess/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/kylevess/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/kylevess/proprietary/etc/wifi/bcmdhd_p2p.bin:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/kylevess/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/kylevess/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/kylevess/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/kylevess/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/kylevess/proprietary/etc/gps/glconfig.xml:system/etc/gps/glconfig.xml \
    vendor/samsung/kylevess/proprietary/lib/egl/libGLES_hawaii.so:system/lib/egl/libGLES_hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/kylevess/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/samsung/kylevess/proprietary/lib/hw/audio.primary.hawaii.so:system/lib/hw/audio.primary.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/audio_policy.hawaii.so:system/lib/hw/audio.primary.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/gps.hawaii.so:system/lib/hw/gps.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/lights.hawaii.so:system/lib/hw/lights.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/sensors.hawaii.so:system/lib/hw/sensors.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/camera.hawaii.so:system/lib/hw/camera.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/gralloc.hawaii.so:system/lib/hw/gralloc.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hw/hwcomposer.hawaii.so:system/lib/hw/hwcomposer.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/kylevess/proprietary/lib/libaacdecoderwrapper.so:system/lib/libaacdecoderwrapper.so \
    vendor/samsung/kylevess/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/samsung/kylevess/proprietary/lib/libatlog.so:system/lib/libatlog.so \
    vendor/samsung/kylevess/proprietary/lib/libat_stubs.so:system/lib/libat_stubs.so \
    vendor/samsung/kylevess/proprietary/lib/libbralloc.so:system/lib/libbralloc.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmaacenc.so:system/lib/libbrcmaacenc.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmamrnbaridec.so:system/lib/libbrcmamrnbaridec.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmamrnbarienc.so:system/lib/libbrcmamrnbarienc.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmamrwbaridec.so:system/lib/libbrcmamrwbaridec.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmamrwbarienc.so:system/lib/libbrcmamrwbarienc.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmcutils.so:system/lib/libbrcmcutils.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmheaacdecoder.so:system/lib/libbrcmheaacdecoder.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmmp3dec.so:system/lib/libbrcmmp3dec.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmmp3enc.so:system/lib/libbrcmmp3enc.so \
    vendor/samsung/kylevess/proprietary/lib/libBrcmOMX_Component.so:system/lib/libBrcmOMX_Component.so \
    vendor/samsung/kylevess/proprietary/lib/libBrcmOMX_Core.so:system/lib/libBrcmOMX_Core.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcmparser.so:system/lib/libbrcmparser.so \
    vendor/samsung/kylevess/proprietary/lib/libcapi2.so:system/lib/libcapi2.so \
    vendor/samsung/kylevess/proprietary/lib/libcate_rpc.so:system/lib/libcate_rpc.so \
    vendor/samsung/kylevess/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/kylevess/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
    vendor/samsung/kylevess/proprietary/lib/libISP.so:system/lib/libISP.so \
    vendor/samsung/kylevess/proprietary/lib/libisp2.so:system/lib/libisp2.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.aac.decoder.so:system/lib/libOMX.brcm.audio.aac.decoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.aac.encoder.so:system/lib/libOMX.brcm.audio.aac.encoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.amrnb.decoder.so:system/lib/libOMX.brcm.audio.amrnb.decoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.amrnb.encoder.so:system/lib/libOMX.brcm.audio.amrnb.encoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.amrwb.decoder.so:system/lib/libOMX.brcm.audio.amrwb.decoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.amrwb.encoder.so:system/lib/libOMX.brcm.audio.amrwb.encoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.mp3.decoder.so:system/lib/libOMX.brcm.audio.mp3.decoder.so \
    vendor/samsung/kylevess/proprietary/lib/libOMX.brcm.audio.mp3.encoder.so:system/lib/libOMX.brcm.audio.mp3.encoder.so \
    vendor/samsung/kylevess/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/kylevess/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/samsung/kylevess/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/kylevess/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/kylevess/proprietary/lib/libseckeyprov.so:system/lib/libseckeyprov.so \
    vendor/samsung/kylevess/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/kylevess/proprietary/lib/libsoc.so:system/lib/libsoc.so \
    vendor/samsung/kylevess/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/kylevess/proprietary/lib/libSoundAlive_VSP_ver312a.so:system/lib/libSoundAlive_VSP_ver312a.so \
    vendor/samsung/kylevess/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/kylevess/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/kylevess/proprietary/lib/libuecodec.so:system/lib/libuecodec.so \
    vendor/samsung/kylevess/proprietary/lib/libusb_config.so:system/lib/libusb_config.so \
    vendor/samsung/kylevess/proprietary/lib/libVCOS.so:system/lib/libVCOS.so \
    vendor/samsung/kylevess/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/kylevess/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/kylevess/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/kylevess/proprietary/lib/libV3D_csc.so:system/lib/libV3D_csc.so \
    vendor/samsung/kylevess/proprietary/lib/libV3D_driver.so:system/lib/libV3D_driver.so \
    vendor/samsung/kylevess/proprietary/lib/libV3D_server.so:system/lib/libV3D_server.so \
    vendor/samsung/kylevess/proprietary/lib/libVCE_imageconv.so:system/lib/libVCE_imageconv.so \
    vendor/samsung/kylevess/proprietary/lib/libVCE_csl.so:system/lib/libVCE_csl.so \
    vendor/samsung/kylevess/proprietary/lib/libVCE_driver.so:system/lib/libVCE_driver.so \
    vendor/samsung/kylevess/proprietary/lib/libvtqinit.so:system/lib/libvtqinit.so \
    vendor/samsung/kylevess/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/kylevess/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/kylevess/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/samsung/kylevess/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
    vendor/samsung/kylevess/proprietary/lib/libbluetooth.so:system/lib/libbluetooth.so \
    vendor/samsung/kylevess/proprietary/lib/libbluetoothd.so:system/lib/libbluetoothd.so \
    vendor/samsung/kylevess/proprietary/lib/libbrcm_ril.so:system/lib/libbrcm_ril.so \
    vendor/samsung/kylevess/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/kylevess/proprietary/lib/libbtio.so:system/lib/libbtio.so \
    vendor/samsung/kylevess/proprietary/lib/libchip_state.so:system/lib/libchip_state.so \
    vendor/samsung/kylevess/proprietary/lib/libclcore.bc:system/lib/libclcore.bc \
    vendor/samsung/kylevess/proprietary/lib/libclcore_neon.bc:system/lib/libclcore_neon.bc \
    vendor/samsung/kylevess/proprietary/lib/libcontainers.so:system/lib/libcontainers.so \
    vendor/samsung/kylevess/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/kylevess/proprietary/lib/libETC1.so:system/lib/libETC1.so \
    vendor/samsung/kylevess/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/kylevess/proprietary/lib/libfmradio_jni.so:system/lib/libfmradio_jni.so \
    vendor/samsung/kylevess/proprietary/lib/libGLES_hawaii.so:system/lib/libGLES_hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/libglib.so:system/lib/libglib.so \
    vendor/samsung/kylevess/proprietary/lib/libgui.so:system/lib/libgui.so \
    vendor/samsung/kylevess/proprietary/lib/libhwui.so:system/lib/libhwui.so \
    vendor/samsung/kylevess/proprietary/lib/libjpeg_turbo.so:system/lib/libjpeg_turbo.so \
    vendor/samsung/kylevess/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \
    vendor/samsung/kylevess/proprietary/lib/libnvaccessor.so:system/lib/libnvaccessor.so \
    vendor/samsung/kylevess/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/kylevess/proprietary/lib/libps_dunmgr.so:system/lib/libps_dunmgr.so \
    vendor/samsung/kylevess/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/kylevess/proprietary/lib/libremotedesktop_client.so:system/lib/libremotedesktop_client.so \
    vendor/samsung/kylevess/proprietary/lib/libremotedesktopservice.so:system/lib/libremotedesktopservice.so \
    vendor/samsung/kylevess/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/kylevess/proprietary/lib/lib_SamsungRec_V01006.so:system/lib/li_SamsungRec_01006.so \
    vendor/samsung/kylevess/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/kylevess/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v04004.so:system/lib/lib_Samsung_SB_AM_for_ICS_v04004.so \
    vendor/samsung/kylevess/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/kylevess/proprietary/lib/lib_SoundAlive_V01013p.so:system/lib/lib_SoundAlive_V01013p.so \
    vendor/samsung/kylevess/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/samsung/kylevess/proprietary/lib/libsthmb.so:system/lib/libsthm.so \
    vendor/samsung/kylevess/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/samsung/kylevess/proprietary/lib/libui.so:system/lib/libui.so \
    vendor/samsung/kylevess/proprietary/lib/libuip.so:system/lib/libuip.so \
    vendor/samsung/kylevess/proprietary/lib/libv3d.so:system/lib/libv3d.so \
    vendor/samsung/kylevess/proprietary/lib/audio.primary.hawaii.so:system/lib/audio.primary.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/audio_policy.hawaii.so:system/lib/audio_policy.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/camera.hawaii.so:system/lib/camera.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/gps.hawaii.so:system/lib/gps.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/gralloc.hawaii.so:system/lib/gralloc.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/hwcomposer.hawaii.so:system/lib/hwcomposer.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/lights.hawaii.so:system/lib/lights.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/sensors.hawaii.so:system/lib/sensors.hawaii.so \
    vendor/samsung/kylevess/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/kylevess/proprietary/lib/modules/dhd.ko:system/lib/modules/dhd.ko \
    vendor/samsung/kylevess/proprietary/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so:system/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so \
    vendor/samsung/kylevess/proprietary/usr/lib/alsa-lib/libbcm_hp_filter.so:system/usr/lib/alsa-lib/libbcm_hp_filter.so \
    vendor/samsung/kylevess/proprietary/usr/lib/alsa-lib/libbcm_test_filter.so:system/usr/lib/alsa-lib/libbcm_test_filter.so \
    vendor/samsung/kylevess/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf
